redis:
    test:
        'on':
            borrow: true
            return: false
spring:
    redis:
        database: 0
        host: localhost
        jedis:
            pool:
                max-active: -1
                max-idle: 5
                max-wait: 30
                min-idle: 5
        password:
            enable: false
        port: 6379
        timeout: 10000
