server:
  servlet:
    context-path: /rbac

#jwt
jwt:
  header: Authorization
  # ????
  token-start-with: Bearer
  # ??Base64????????
  base64-secret: Y21GaVkzQmhkM2R5YjJSbVlXWmhjMlJtY21GaVkzQmhkM2R5YjJSbVlXWmhjMlJtY21GaVkzQmhkM2R5YjJSbVlXWmhjMlJtY21GaVkzQmhkM2R5YjJSbVlXWmhjMlJt
  # ?????? ????/??
  token-validity-in-seconds: 14400000

spring:
  datasource:
    url: jdbc:p6spy:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/rbac?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    hikari:
      max-lifetime: 30000
      pool-name: rbacpool
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
